server:
  port: 1000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: qd_route
          uri: http://www.qidian.com
          predicates:
            - Path=/qd


logging: ## Spring Cloud Gateway的日志配置
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: '*'